mysql-data:
  container_name: mysql-data
  image: ubuntu:wily
  volumes:
    - /var/lib/mysql
mysql:
  container_name: mysql
  image: mysql/mysql-server:5.6.28
  expose:
    - "3306"
  volumes_from:
    - mysql-data
  environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    - TCP_PORTS=3306
wordpress-data:
  container_name: wordpress-data
  image: ubuntu:wily
  volumes:
    - /var/www/html/
wordpress:
  container_name: wordpress
  image: wordpress:4.4.2
  volumes_from:
    - wordpress-data
  links:
    - "mysql:mysql"
  ports:
    - "80:80"
  expose:
    - "80"
